### ISSUE TITLE
RangeError: Offset is outside the bounds of the DataView

### ISSUE THREAD

**Issue by joonhocho** [terkelg/exifer#2]
```
instrument.js:102 RangeError: Offset is outside the bounds of the DataView
    at DataView.getUint32 (<anonymous>)
    at readTags$1 (exifer.umd.js:366)
    at parseTiffSegment (exifer.umd.js:352)
    at Object.parseExif [as tiff] (exifer.umd.js:337)
    at exifer (exifer.umd.js:478)
```
tested with https://github.com/ianare/exif-samples/blob/master/jpg/orientation/landscape_1.jpg

**Comment by terkelg** [comment]
Thank you. Can you share a minimal version of your code?

**Comment by daliusd** [comment]
I have tested with same samples - no problem.

**Comment by terkelg** [comment]
Thank you so much @daliusd for helping out here! I appreciate it. I think I'll go ahead and close this one then 👍
