### ISSUE TITLE
how to get focal length

### ISSUE THREAD

**Issue by Jeongyong-park** [terkelg/exifer#3]
i tried this code for get focallength in exifer but i can't

``` javascript
   var focallength = {
        0x920a: { name: 'FocalLength' },
        0xa405: { name: 'FocalLengthIn35mmFilm' },
    };
    tags = await exifer(imageBuffer, { tags: { exif, focallength } });
    if (tags.hasOwnProperty('Orientation')) {
        return tags.Orientation;
    }
```

**Comment by terkelg** [comment]
Do you know if that field is present in the image?

**Comment by Jeongyong-park** [comment]
This picture is the file I tested.

and I was finally able to get the value I wanted through a library called **exifr** not exifer.

![DJI_0001 (1)](https://user-images.githubusercontent.com/6187128/94246184-5ebdf880-ff56-11ea-8ca4-f2a51fc3e450.JPG)
